### ISSUE TITLE
Issue while replicating CivilComments training results

### ISSUE THREAD

**Issue by LuoyaoChen** [izmailovpavel/spurious_feature_learning#7]
Hi, 

I am trying to replicate the CivilComments training results, and I used exactly the .bash command as indicated in the README.
i.e. I train 10 epoch, using 
```
python3 train_supervised.py \
    --output_dir=logs/civilcomments/erm_seed1 \
	--num_epochs=10 \
    --eval_freq=1 \
    --save_freq=10 \
    --seed=1 \
	--weight_decay=1.e-4 \
    --batch_size=16 \
    --init_lr=1e-5 \
	--scheduler=bert_lr_scheduler \
    --data_dir=./data \
	--data_transform=BertTokenizeTransform \
	--dataset=WildsCivilCommentsCoarse \
    --model=bert_pretrained \
	--optimizer=bert_adamw_optimizer
``` 

The error at step 15518, 

```
Loss: 0.028 (0.187188); Acc: 1.000000:  92%|█████████▏| 15518/16815 [39:02<03:15,  6.62it/s]

```

Error message says 

```python
Traceback (most recent call last):
  File "spurious_feature_learning/train_supervised.py", line 118, in <module>
    main(args)
  File "spurious_feature_learning/train_supervised.py", line 71, in main
    loss_meter, acc_groups, example_images = supervised_utils.train_epoch(
  File "spurious_feature_learning/utils/supervised_utils.py", line 14, in train_epoch
    for batch in (pbar := tqdm.tqdm(loader)):
  File "home/miniconda3/envs/spurious_feature_learning/lib/python3.10/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "home/miniconda3/envs/spurious_feature_learning/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
    data = self._next_data()
  File "home/miniconda3/envs/spurious_feature_learning/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1346, in _next_data
    return self._process_data(data)
  File "home/miniconda3/envs/spurious_feature_learning/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1372, in _process_data
    data.reraise()
  File "home/miniconda3/envs/spurious_feature_learning/lib/python3.10/site-packages/torch/_utils.py", line 722, in reraise
    raise exception
ValueError: Caught ValueError in DataLoader worker process 14.
Original Traceback (most recent call last):
  File "home/miniconda3/envs/spurious_feature_learning/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "home/miniconda3/envs/spurious_feature_learning/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "home/miniconda3/envs/spurious_feature_learning/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "spurious_feature_learning/data/datasets.py", line 273, in __getitem__
    x, y, metadata = self.dataset[idx]
  File "home/miniconda3/envs/spurious_feature_learning/lib/python3.10/site-packages/wilds/datasets/wilds_dataset.py", line 503, in __getitem__
    x = self.transform(x)
  File "spurious_feature_learning/data/data_transforms.py", line 182, in __call__
    tokens = self.tokenizer(
  File "home/miniconda3/envs/spurious_feature_learning/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2858, in __call__
    encodings = self._call_one(text=text, text_pair=text_pair, **all_kwargs)
  File "home/miniconda3/envs/spurious_feature_learning/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2916, in _call_one
    raise ValueError(
ValueError: text input must be of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).

``` 
I think there is a corruption in the dataset, even I enable Download=True. 

Do you have any insights on how to debug it?

Thanks!

**Comment by izmailovpavel** [comment]
Hey @LuoyaoChen, I did not run into this myself. The dataset is just loaded from WILDS, I believe: https://github.com/izmailovpavel/spurious_feature_learning/blob/main/data/datasets.py#L203. You can try to load the dataset manually and check that you can access all of the datapoints. If you identify a faulty datapoint, you can try to drop it from the dataset. It could also be a good idea to try to re-download the dataset, or start an issue in https://github.com/p-lambda/wilds/ if you can reproduce it using wilds-only code.
